apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"                      
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""        #CLIENT_ID=$(az aks show -g $RG -n $CLUSTER --query addonProfiles.azureKeyvaultSecretsProvider.identity.clientId -o tsv)
    keyvaultName: "twobcloud123" 
    cloudName: ""         
    objects: |
      array:
        - |
          objectName: "my-secret"
          objectType: secret
          objectVersion: "" 
    tenantId: ""                        #AZURE_TENANT_ID=$(az account show --query tenantId -o tsv)
  secretObjects:                                
      type: Opaque
      data:
        - objectName: "my-secret"
          key: my-secret




#CLIENT_ID=$(az aks show -g Peter-Candidate -n regular-cod-aks --query addonProfiles.azureKeyvaultSecretsProvider.identity.clientId -o tsv)
